### ISSUE TITLE
Add a TypeScript declaration file

### ISSUE THREAD

**Issue by lucasrmendonca** [eight04/webext-launch-web-auth-flow#12]
It would be nice to add a [TypeScript declaration file](https://www.typescriptlang.org/docs/handbook/declaration-files/introduction.html), so users using TypeScript can see Type errors (especially since this library requires the "redirect_uri" parameter, while the original launchWebAuthFlow does not).

Here's an example of how VSCode would inform the user in TS that a property is missing:

![typescript-error](https://user-images.githubusercontent.com/5521917/201505004-6ba657a9-3d65-4ec6-afee-1ae53434e983.png)

**Comment by eight04** [comment]
Would it be better to use JSDoc comment? So the declaration stay with the source. Can typescript pick them automatically?

**Comment by lucasrmendonca** [comment]
Although TypeScript can pick JSDoc comments, I decided to use a separate file on purpose because it felt less noisy and more organized this way. Also JSDoc syntax quickly becomes vertically repetitive so the *.d.ts syntax seemed like a cleaner and easier to read alternative.

What do you think?
